#!/bin/bash
echo "CONDA-BASHRC 2"

if [ -f ~/.bashrc ]
then
    source ~/.bashrc
fi

function condapy() {
     local RED="\[\033[0;31m\]"
     PATH=$HOME/anaconda2/bin:$PATH
     export PS1="$RED[CONDA2] $PS1"
 }

condapy

alias ipy='jupyter qtconsole'
alias startnb='jupyter notebook'
alias nb2pdf='jupyter nbconvert --to latex --post PDF'
condaforge() { conda install -c conda-forge "$@" ;}
