#!/bin/bash
PROJECTS_HOME="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"
echo "PROJECTS_HOME: $PROJECTS_HOME"

# Copy files to HOME_DIR
cp_autobash() {
    /bin/cp /etc/skel/.bashrc ~/
    cat $PROJECTS_HOME/autobash/bashrc_append >> ~/.bashrc
    echo "copied bashrc"
    cp $PROJECTS_HOME/autobash/aliases ~/.bash_aliases
    echo "copied bash_aliases"
    cp $PROJECTS_HOME/autobash/conda_bashrc2 ~/.conda_bashrc2
    echo "copied conda_bashrc2"
    cp $PROJECTS_HOME/autobash/conda_bashrc3 ~/.conda_bashrc3
    echo "copied conda_bashrc3"
    wget -O ~/.fzf_snippets https://gist.githubusercontent.com/nitred/84e11ef8b96454d39e9639ab82d9058a/raw/4e2528d46777efab353e9a0178560ccaef60829c/.fzf_snippets
    # cp $PROJECTS_HOME/autobash/fzf_snippets ~/.fzf_snippets
    echo "downloaded fzf_snippets"
}
cp_autobash

# SOURCE PROJECTS FILE TO APPEND ~/.bash_aliases and create ~/.bashtk
source $PROJECTS_HOME/autobash/projects $PROJECTS_HOME

# SOURCE BASHRC
source ~/.bashrc
