#!/bin/bash
PROJECTS_HOME="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"
echo "PROJECTS_HOME: $PROJECTS_HOME"
LOCAL_AUTOBASH_DIR=~/.autobash
echo "LOCAL_AUTOBASH_DIR: $LOCAL_AUTOBASH_DIR"
PYTHON_PATH=~/anaconda3/bin/python
echo "PYTHON_PATH: $PYTHON_PATH"
PIP_PATH=~/anaconda3/bin/pip
echo "PIP_PATH: $PIP_PATH"


# Copy files to HOME_DIR
cp_autobash() {
    /bin/cp /etc/skel/.bashrc ~/
    cat $PROJECTS_HOME/autobash/bashrc_append >> ~/.bashrc
    echo "copied bashrc"
    cp $PROJECTS_HOME/autobash/aliases ~/.bash_aliases
    echo "copied bash_aliases"
    cp $PROJECTS_HOME/autobash/conda_bashrc2 ~/.conda_bashrc2
    echo "copied conda_bashrc2"
    cp $PROJECTS_HOME/autobash/conda_bashrc3 ~/.conda_bashrc3
    echo "copied conda_bashrc3"
    wget -O ~/.fzf_snippets https://gist.githubusercontent.com/nitred/84e11ef8b96454d39e9639ab82d9058a/raw/.fzf_snippets
    echo "downloaded fzf_snippets"
}
cp_autobash


# SETUP LOCAL AUTOBASH DIRECTORIES AND DEPENDENCIES
source $PROJECTS_HOME/autobash/local_autobash_setup "$LOCAL_AUTOBASH_DIR" "$PIP_PATH"


# SOURCE PROJECTS FILE TO APPEND ~/.bash_aliases and create ~/.autobash
source $PROJECTS_HOME/autobash/projects $PROJECTS_HOME


# UPDATING TOOL ALIASES IN BASH_ALIASES
echo "" >> ~/.bash_aliases
echo "# autobash-tools" >> ~/.bash_aliases
echo "alias autobash-get-protemplates='$PYTHON_PATH $PROJECTS_HOME/autobash/tools/protemplates.py --local_directory "$LOCAL_AUTOBASH_DIR"'" >> ~/.bash_aliases
echo "alias autobash-get-rmate='$PYTHON_PATH $PROJECTS_HOME/autobash/tools/rmate.py --local_directory "$LOCAL_AUTOBASH_DIR"'" >> ~/.bash_aliases
echo "alias autobash-get-youtube-dl='$PYTHON_PATH $PROJECTS_HOME/autobash/tools/youtube-dl.py --local_directory "$LOCAL_AUTOBASH_DIR"'" >> ~/.bash_aliases


# SOURCE BASHRC
source ~/.bashrc
