#!/bin/bash
LOCAL_AUTOBASH_DIR=$1
PIP_PATH=$2
echo "##########################################################################"
echo "LOCAL AUTOBASH SETUP: LOCAL_AUTOBASH_DIR: $LOCAL_AUTOBASH_DIR"
echo "LOCAL AUTOBASH SETUP: PIP_PATH: $PIP_PATH"


################################################################################
# Local autobash directories
################################################################################
LOCAL_AUTOBASH_DIR=~/.autobash
LOCAL_AUTOBASH_SRC=$LOCAL_AUTOBASH_DIR/src
LOCAL_AUTOBASH_BIN=$LOCAL_AUTOBASH_DIR/bin
LOCAL_AUTOBASH_LIB=$LOCAL_AUTOBASH_DIR/lib


################################################################################
# Create local directories
################################################################################
echo "##########################################################################"
echo "LOCAL_AUTOBASH_DIR: $LOCAL_AUTOBASH_DIR"
echo "CREATING LOCAL_AUTOBASH_DIR directory: $LOCAL_AUTOBASH_DIR"
mkdir -p $LOCAL_AUTOBASH_DIR

echo "##########################################################################"
echo "LOCAL_AUTOBASH_SRC: $LOCAL_AUTOBASH_SRC"
echo "CREATING LOCAL_AUTOBASH_SRC directory: $LOCAL_AUTOBASH_SRC"
mkdir -p $LOCAL_AUTOBASH_SRC

echo "##########################################################################"
echo "LOCAL_AUTOBASH_BIN: $LOCAL_AUTOBASH_BIN"
echo "CREATING LOCAL_AUTOBASH_BIN directory: $LOCAL_AUTOBASH_BIN"
mkdir -p $LOCAL_AUTOBASH_BIN

echo "##########################################################################"
echo "LOCAL_AUTOBASH_BIN: $LOCAL_AUTOBASH_LIB"
echo "CREATING LOCAL_AUTOBASH_LIB directory: $LOCAL_AUTOBASH_LIB"
mkdir -p $LOCAL_AUTOBASH_LIB


################################################################################
# Install pip packages
################################################################################
echo "##########################################################################"
echo "Installing required python packages"
$PIP_PATH install configobj requests
